/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersEditRouteImport } from './routes/users/edit'
import { Route as UsersUseridIndexRouteImport } from './routes/users/$userid/index'
import { Route as PostsPostidIndexRouteImport } from './routes/posts/$postid/index'
import { Route as UsersUseridFollowRequestsRouteImport } from './routes/users/$userid/follow-requests'
import { Route as PostsPostidEditRouteImport } from './routes/posts/$postid/edit'
import { Route as PostsPostidCommentsCommentidIndexRouteImport } from './routes/posts/$postid/comments/$commentid/index'
import { Route as PostsPostidCommentsCommentidEditRouteImport } from './routes/posts/$postid/comments/$commentid/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersEditRoute = UsersEditRouteImport.update({
  id: '/users/edit',
  path: '/users/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUseridIndexRoute = UsersUseridIndexRouteImport.update({
  id: '/users/$userid/',
  path: '/users/$userid/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostidIndexRoute = PostsPostidIndexRouteImport.update({
  id: '/posts/$postid/',
  path: '/posts/$postid/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUseridFollowRequestsRoute =
  UsersUseridFollowRequestsRouteImport.update({
    id: '/users/$userid/follow-requests',
    path: '/users/$userid/follow-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsPostidEditRoute = PostsPostidEditRouteImport.update({
  id: '/posts/$postid/edit',
  path: '/posts/$postid/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostidCommentsCommentidIndexRoute =
  PostsPostidCommentsCommentidIndexRouteImport.update({
    id: '/posts/$postid/comments/$commentid/',
    path: '/posts/$postid/comments/$commentid/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsPostidCommentsCommentidEditRoute =
  PostsPostidCommentsCommentidEditRouteImport.update({
    id: '/posts/$postid/comments/$commentid/edit',
    path: '/posts/$postid/comments/$commentid/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/users/edit': typeof UsersEditRoute
  '/posts/$postid/edit': typeof PostsPostidEditRoute
  '/users/$userid/follow-requests': typeof UsersUseridFollowRequestsRoute
  '/posts/$postid': typeof PostsPostidIndexRoute
  '/users/$userid': typeof UsersUseridIndexRoute
  '/posts/$postid/comments/$commentid/edit': typeof PostsPostidCommentsCommentidEditRoute
  '/posts/$postid/comments/$commentid': typeof PostsPostidCommentsCommentidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/users/edit': typeof UsersEditRoute
  '/posts/$postid/edit': typeof PostsPostidEditRoute
  '/users/$userid/follow-requests': typeof UsersUseridFollowRequestsRoute
  '/posts/$postid': typeof PostsPostidIndexRoute
  '/users/$userid': typeof UsersUseridIndexRoute
  '/posts/$postid/comments/$commentid/edit': typeof PostsPostidCommentsCommentidEditRoute
  '/posts/$postid/comments/$commentid': typeof PostsPostidCommentsCommentidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/users/edit': typeof UsersEditRoute
  '/posts/$postid/edit': typeof PostsPostidEditRoute
  '/users/$userid/follow-requests': typeof UsersUseridFollowRequestsRoute
  '/posts/$postid/': typeof PostsPostidIndexRoute
  '/users/$userid/': typeof UsersUseridIndexRoute
  '/posts/$postid/comments/$commentid/edit': typeof PostsPostidCommentsCommentidEditRoute
  '/posts/$postid/comments/$commentid/': typeof PostsPostidCommentsCommentidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/login'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/users/edit'
    | '/posts/$postid/edit'
    | '/users/$userid/follow-requests'
    | '/posts/$postid'
    | '/users/$userid'
    | '/posts/$postid/comments/$commentid/edit'
    | '/posts/$postid/comments/$commentid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/login'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/users/edit'
    | '/posts/$postid/edit'
    | '/users/$userid/follow-requests'
    | '/posts/$postid'
    | '/users/$userid'
    | '/posts/$postid/comments/$commentid/edit'
    | '/posts/$postid/comments/$commentid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/login'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/users/edit'
    | '/posts/$postid/edit'
    | '/users/$userid/follow-requests'
    | '/posts/$postid/'
    | '/users/$userid/'
    | '/posts/$postid/comments/$commentid/edit'
    | '/posts/$postid/comments/$commentid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  UsersEditRoute: typeof UsersEditRoute
  PostsPostidEditRoute: typeof PostsPostidEditRoute
  UsersUseridFollowRequestsRoute: typeof UsersUseridFollowRequestsRoute
  PostsPostidIndexRoute: typeof PostsPostidIndexRoute
  UsersUseridIndexRoute: typeof UsersUseridIndexRoute
  PostsPostidCommentsCommentidEditRoute: typeof PostsPostidCommentsCommentidEditRoute
  PostsPostidCommentsCommentidIndexRoute: typeof PostsPostidCommentsCommentidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/edit': {
      id: '/users/edit'
      path: '/users/edit'
      fullPath: '/users/edit'
      preLoaderRoute: typeof UsersEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userid/': {
      id: '/users/$userid/'
      path: '/users/$userid'
      fullPath: '/users/$userid'
      preLoaderRoute: typeof UsersUseridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postid/': {
      id: '/posts/$postid/'
      path: '/posts/$postid'
      fullPath: '/posts/$postid'
      preLoaderRoute: typeof PostsPostidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userid/follow-requests': {
      id: '/users/$userid/follow-requests'
      path: '/users/$userid/follow-requests'
      fullPath: '/users/$userid/follow-requests'
      preLoaderRoute: typeof UsersUseridFollowRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postid/edit': {
      id: '/posts/$postid/edit'
      path: '/posts/$postid/edit'
      fullPath: '/posts/$postid/edit'
      preLoaderRoute: typeof PostsPostidEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postid/comments/$commentid/': {
      id: '/posts/$postid/comments/$commentid/'
      path: '/posts/$postid/comments/$commentid'
      fullPath: '/posts/$postid/comments/$commentid'
      preLoaderRoute: typeof PostsPostidCommentsCommentidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postid/comments/$commentid/edit': {
      id: '/posts/$postid/comments/$commentid/edit'
      path: '/posts/$postid/comments/$commentid/edit'
      fullPath: '/posts/$postid/comments/$commentid/edit'
      preLoaderRoute: typeof PostsPostidCommentsCommentidEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  UsersEditRoute: UsersEditRoute,
  PostsPostidEditRoute: PostsPostidEditRoute,
  UsersUseridFollowRequestsRoute: UsersUseridFollowRequestsRoute,
  PostsPostidIndexRoute: PostsPostidIndexRoute,
  UsersUseridIndexRoute: UsersUseridIndexRoute,
  PostsPostidCommentsCommentidEditRoute: PostsPostidCommentsCommentidEditRoute,
  PostsPostidCommentsCommentidIndexRoute:
    PostsPostidCommentsCommentidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
